JDP230301-3
mps4dev/project-jdp-2303-01 pull request #7
Opened 2023-03-03 13:00 UTC by jakubantonik

2023-03-03 13:33 UTC, szmuraj requested changes

2023-03-03 13:33 UTC, szmuraj commented on build.gradle
> +    compileOnly 'org.projectlombok:lombok:1.18.26'
Czy nie powinniśmy lomnoka również dać w nawiasy by kod był spójny.

2023-03-03 13:33 UTC, szmuraj commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public ResponseEntity<Void> createCart(@RequestBody CartDto cartDto){
DTO czy Dto?

2023-03-03 13:33 UTC, szmuraj commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +        }
Brakuje @Put

2023-03-03 13:33 UTC, szmuraj commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @PostMapping(value = "createOrder", consumes = MediaType.APPLICATION_JSON_VALUE)
Po co 2x @Post?

2023-03-03 13:40 UTC, domKul commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public ResponseEntity<Void> createCart(@RequestBody CartDto cartDto){
DTO

2023-03-03 13:42 UTC, domKul commented on src/main/java/com/kodilla/ecommercee/CartDto.java
> +public class CartDto {
dodaj pakiet gdzie umiescisz CartDTO 
**com.kodilla.ecommercee.dto**

2023-03-03 20:21 UTC, mps4dev requested changes

2023-03-03 20:21 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @PostMapping(value = "createCart", consumes = MediaType.APPLICATION_JSON_VALUE)
usun value = "createCart" -(POST v1/carts wystarczy)

2023-03-03 20:21 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public ResponseEntity<Void> deleteElement(@PathVariable Long itemId) {
Element? My tu mamy sklep, a nie hurtownie elementow

2023-03-03 20:21 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +        public ResponseEntity<Void> createOrder(){
CreateOrder w CartController?

2023-03-06 18:26 UTC, Staszewskip approved these changes

2023-03-06 18:46 UTC, domKul approved these changes

2023-03-07 07:28 UTC, mps4dev requested changes

2023-03-07 07:28 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public ResponseEntity<CartDTO> addItemToCart(@PathVariable Long itemId){
No dobra, mamy itemId, a do ktorego koszyka go dodac? Czy nie powinien to byc url /v1/carts/{cartId}?productId=blablabla ?

2023-03-07 07:28 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @DeleteMapping(value = "{itemId}")
co to jest itemId? Nie lepiej cartId?

2023-03-07 07:28 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @PostMapping(value = "createOrderFromCart", consumes = MediaType.APPLICATION_JSON_VALUE)
Po co takie skomplikowane urle? Nie wystarczy v1/carts/{cartId}/order ?I czegos brakuje, prawda? Moze przynajmniej cartId?

2023-03-07 07:28 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public ResponseEntity<List<CartDTO>> getItemsFromCart(){
Brakuje mi chyba getCartById

2023-03-07 07:28 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public ResponseEntity<CartDTO> addItemToCart(@PathVariable Long itemId){
Alternatywnie mogloby byc updateCart(CartDto cart)

2023-03-08 17:33 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public ResponseEntity<Void> createCart(@RequestBody CartDTO cartDto){
komentarz

2023-03-10 20:27 UTC, Staszewskip approved these changes

2023-03-10 20:44 UTC, merged